import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  container: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    position: 'absolute',
    top: '40%',
  },
  modalView: {
    minHeight: 200,
    minWidth: 360,
    width: '60%',
    maxWidth: '80%',
    borderRadius: 20,
    paddingVertical: 25,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#6d6d6da5',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowRadius: 8,
    elevation: 0,
  },
  credentialContainer: {
    width: '70%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    flex: 1,
  },
  inputContainer: {
    width: '80%',
    paddingHorizontal: 28,
  },
  formInput: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'flex-end',
    paddingVertical: 12,
  },
  buttonContainer: {
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingHorizontal: 28,
    paddingTop: 22,
  },
  button: {
    paddingVertical: 12,
    paddingHorizontal: 38,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 2,
  },
  buttonText: {},
  cancelButton: {
    backgroundColor: '#d55252',
    paddingVertical: 12,
    paddingHorizontal: 38,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#d55252',
  },
  modalInputContainer: {
    width: '100%',
    paddingHorizontal: 28,
  },
  subText: {
    fontSize: 10,
    color: '#3f3f3f',
    paddingHorizontal: 12,
    paddingTop: 5,
  },
  profileInformationContainer: {
    paddingVertical: 20,
    width: '70%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nameContainer: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 8,
    paddingBottom: 6,
  },
  addressContainer: {},
  localityContainer: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingBottom: 16,
  },
});
