import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    position: 'absolute',
    top: '40%',
  },
  modalView: {
    borderRadius: 20,
    paddingVertical: 25,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#6d6d6da5',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowRadius: 8,
    elevation: 0,
  },
  input: {
    borderWidth: 1.5,
    borderColor: '#3f3f3f',
    marginTop: 6,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 10,
  },
  inputContainer: {
    width: '80%',
    paddingHorizontal: 28,
  },
  buttonContainer: {
    width: '80%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
    paddingHorizontal: 28,
  },
  button: {
    width: '100%',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1.5,
  },
  buttonOutline: {
    marginTop: 5,
    borderColor: '#5346c4',
    borderWidth: 1.5,
    width: '100%',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  buttonText: {},
  cancelButton: {
    backgroundColor: '#d55252',
    width: '100%',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 5,
  },
  modalInputContainer: {
    width: '100%',
    paddingHorizontal: 28,
  },
  subText: {
    fontSize: 10,
    color: '#3f3f3f',
    paddingHorizontal: 12,
    paddingTop: 5,
  },
  profileInformationContainer: {
    paddingVertical: 10,
  },
  label: {
    paddingVertical: 8,
    fontSize: 18,
    fontWeight: 'bold',
  },
  nameContainer: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 8,
    paddingBottom: 6,
  },
  addressContainer: {},
  localityContainer: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingBottom: 16,
  },
});
