import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  container: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    position: 'absolute',
    top: '30%',
    zIndex: 1,
  },
  modalView: {
    minHeight: 200,
    minWidth: 480,
    width: '60%',
    maxWidth: 600,
    borderRadius: 20,
    paddingVertical: 25,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#6d6d6da5',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowRadius: 8,
    elevation: 0,
  },
  credentialContainer: {
    width: '84%',
    maxWidth: 400,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    flex: 1,
  },
  nameInput: {
    flex: 1,
    textAlign: 'center',
    fontWeight: '700',
    fontSize: 22,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  formLabel: {
    minWidth: '30%',
    width: '35%',
  },
  inputContainer: {
    width: '80%',
  },
  formInput: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'baseline',
    paddingVertical: 12,
  },
  buttonContainer: {
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingHorizontal: 28,
    paddingTop: 22,
  },
  button: {
    paddingVertical: 12,
    paddingHorizontal: 38,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 2,
  },
  buttonText: {},
  cancelButton: {
    backgroundColor: '#d55252',
    paddingVertical: 12,
    paddingHorizontal: 38,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#d55252',
  },
  modalInputContainer: {
    width: '100%',
    paddingHorizontal: 28,
  },
  profileInformationContainer: {
    paddingVertical: 20,
    width: '70%',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
